[[headers]]
 for = "/*"
  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  must-revalidate'''

[functions]

  # Specifies `esbuild` for functions bundling
  # to support optional chaining
  node_bundler = "esbuild"